reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
chain_width = 40
ignore = [
    "crates/tycho-substreams/src/pb",
    "crates/tycho-substreams/src/abi",
    "ethereum-balancer-v2/src/abi",
    "ethereum-sfraxeth/src/abi",
    "ethereum-sfrax/src/abi",
    "ethereum-curve/src/abi",
    "ethereum-uniswap-v2/src/abi",
    "ethereum-uniswap-v3/src/abi",
    "ethereum-uniswap-v3-logs-only/src/abi",
]
