[package]
name = "tycho-substreams"
version = "0.2.0"
edition = "2021"

[dependencies]
substreams-ethereum.workspace = true
substreams.workspace = true
prost.workspace = true
hex.workspace = true
itertools = "0.12.0"
ethabi.workspace = true
num-bigint = "0.4.4"
